var vehicleTypeMapping = {
    "002": "Sedans - Compact - Midsize (002 Series is Finished, use 020)",
    "003": "Sedans - Midsize - Full Size",
    "004": "Sedans - Station Wagons",
    "005": "SUV - Marked, Unmarked Cruisers, Interceptors Utility",
    "006": "Sedans - Full Size",
    "007": "Sedans - Marked, Unmarked Cruisers, Interceptors",
    "020": "Sedans - Compact - Midsize",
    "041": "Sport Utility Vehicle (SUV) - Jeep 4x2, 4x4",
    "042": "Pickup Truck - Compact - Standard Cab 4x2, 4x4",
    "043": "Pickup Truck - Half Ton - Standard Cab 4x2, 4x4",
    "044": "Pickup Truck - Half Ton - Extended Cab 4x2",
    "045": "Pickup Truck - Half Ton - Extended Cab 4x4",
    "046": "Pickup Truck - Compact - Crew Cab 4x2, 4x4",
    "047": "Pickup Truck - Compact - Extended Cab 4x2",
    "048": "Pickup Truck - Half Ton - Crew Cab 4x2",
    "049": "Pickup Truck - Half Ton - Standard Cab 4x4 ",
    "050": "Pickup Truck - Half Ton - Crew Cab 4x4",
    "051": "Pickup Truck - Compact - Extended Cab 4x4",
    "061": "Pickup Truck - Three Quarter Ton - Standard Cab 4x2",
    "062": "Pickup Truck - Three Quarter Ton - Extended Cab 4x2",
    "063": "Pickup Truck - Three Quarter Ton - Crew Cab 4x2",
    "064": "Pickup Truck - Three Quarter Ton - Standard Cab 4x4",
    "065": "Pickup Truck - Three Quarter Ton - Extended Cab 4x4",
    "066": "Truck Chassis - Three Quarter Ton - Any Custom Body 4x2, 4x4",
    "067": "Pickup Truck - Three Quarter Ton - Crew Cab 4x4",
    "071": "Pickup Truck - One Ton - Standard Cab 4x2",
    "073": "Pickup Truck - One Ton - Crew Cab 4x2",
    "074": "Pickup Truck - One Ton - Standard Cab 4x4",
    "075": "Pickup Truck - One Ton - Extended Cab 4x4",
    "076": "Pickup Truck - One Ton - Crew Cab 4x4",
    "077": "Truck Utility - F350H.D. - Standard Cab 4x2 and 4x4",
    "078": "Truck Utility - F350H.D. - Crew Cab 4x2 and 4x4",
    "079": "Truck Utility - F350H.D. - Utility Body - Extended Cab 4x2 and 4x4",
    "080": "Truck Utility - F450H.D. - F550H.D. w or wo Compressor Attachement",
    "094": "Van - Mini Passenger Standard",
    "095": "Van - Mini Cargo Standard",
    "096": "Van - Mini Passenger Extended",
    "097": "Van - Mini Cargo Extended",
    "098": "Van - Mini  Wheelchair Accessible",
    "111": "Van - E150 (equivalent) Cargo Standard",
    "112": "Van - E250 (equivalent) Cargo Standard",
    "113": "Van - E250 (equivalent) Cargo Extended",
    "114": "Van - E350 (equivalent) Cargo Standard",
    "115": "Van - E350 (equivalent) Cargo Extended",
    "126": "Van - E-Series (equivalent) - Extended Body Club Wagon (equivalent) WindowPassenger Van",
    "127": "Van - E-Series (equivalent) - Standard Body Club Wagon (equivalent) Window Passenger Van",
    "135": "Van - Cube E350-E450-F450-F550 (equivalent)",
    "136": "Van - Cube E350 - E450 (equivalent) Crew Cab",
    "137": "Van - Cube - Aerodynamic",
    "145": "Van - Forward Control (Bread Van Type) ",
    "146": "Bus - Passenger Bus",
    "147": "Bus - Mobile Office - Command Centre",
    "154": "Truck - Dump F350-F550 (equivalent) Standard Cab wowo Crane",
    "155": "Truck - Dump F350-F550 (equivalent) Extended Cab wowo Crane",
    "156": "Truck - Dump F350-F550 (equivalent) Crew Cab wowo Crane",
    "157": "Truck - Dump Single Axle (up to 13999kg) or Stake Body wowo Hoist",
    "158": "Truck - Dump Single Axle (above 14000kg) or Stake Body wowo Hoist",
    "159": "Truck - Dump Chipper Single Axle",
    "160": "Truck - Dump Aerial Utility Type",
    "161": "Truck - Cube Van Body Rear Open Furniture Truck",
    "175": "Truck - Dump & Salt Spreader & Plow (all salt & snow equipment)",
    "176": "Truck - Dump & Crane Single Axle wowo Plow and Hoist",
    "177": "Truck - Dump & Crane Single Axle Crew Cab wowo Plow",
    "187": "Truck - Dump Tandem - Tri Axle wowo salt spreader",
    "188": "Truck - Dump Tandem Axle wowo Crane",
    "189": "Truck Chassis - Class 8 - Utility Body & Crane Single Axle",
    "190": "Truck Chassis - Class 8 - Tandem Axle - Flatbed Body With Crane",
    "191": "Truck Chassis - Class 8 - Flatbed Body, Safety Attenuator TC-12 Directional Arrowboard",
    "192": "Truck Chassis - Class 5,6,7,8 - Flatbed Asphalt, Pot Hole Patcher Body - Non Dumping",
    "193": "Truck Chassis - Class 6,7 - Flatbed Tilt and Load Body (Not Roll-off)",
    "194": "Truck Chassis - Class 6,7 - Cube Van Body",
    "195": "Truck Chassis - Class 8 - Tandem Axle - Steerable Lift Axle - Dump Body",
    "196": "Truck - Utility Body & Crane Single Axle Non Dumping",
    "201": "Van Cargo - Class 2,3 - Aerial Device, Bucket Truck",
    "202": "Truck Chassis - Class 6,7 - Single Axle - Chipper Dump Body, Aerial Tower, Bucket Truck",
    "203": "Truck Chassis - Class 8 - Tandem Axle - Flatbed Dump Body, Stick Boom Crane",
    "204": "Truck Chassis - Hydro Excavation, Sewer, Vacuum Body",
    "205": "Truck Chassis - Roll-off System",
    "206": "Truck Chassis - Class 8 - Tandem Axle - Highway Tractor",
    "207": "Truck Chassis - Class 8 - Tanker, Street Flusher",
    "208": "Truck Chassis - Class 4,5 - Utility Body, Aerial Device, Bucket Truck",
    "209": "Truck Chassis - Septic, Toilet Tanker Body",
    "222": "Truck Chassis - Class 4,5,6 - Single Axle - Rear Load Refuse Packer",
    "223": "Truck Chassis - Class 6,7 - Single Axle - Manual Side Load Refuse Packer",
    "224": "Truck Chassis - Class 4,5 - Single Axle - Manual Side Load Refuse Packer",
    "225": "Truck Chassis - Single Sided Recycling Truck",
    "226": "Truck Chassis - Truck Chassis - Double Sided Recycling Truck",
    "227": "Truck - Refuse, Bin Lifting System",
    "236": "Truck - Refuse - Class 8 - Tandem Axle - Rear Packer",
    "237": "Truck - Refuse, Tandem Axle - Side Packer",
    "238": "Truck - Refuse, Tandem Axle - Front Bulk Loading",
    "248": "Semi Trailer - All Axle - Opened Top Waste Transfer Dump Trailer",
    "250": "2505 - Semi Trailer - All Axle - Opened-Closed Top Waste Transfer Trailer (Walking Floor)",
    "250": " Semi Trailer - All Axle - Closed Top Waste Transfer Trailer (Walking Floor)",
    "266": "Trailer - single Axle",
    "267": "Trailer - Tandem Axle",
    "268": "Trailer - Tandem - Tri Axle - Float",
    "269": "Trailer - Arrow Board",
    "270": "Trailer - Cargo Type Trailer-Office Trailer",
    "271": "Trailer Roll-Off Flat Deck",
    "272": "Trailer - Horse",
    "273": "Trailer - Stage",
    "274": "Trailer - Portable Message Sign Board",
    "285": "Trailer - Compressor",
    "286": "Trailer - Generator",
    "287": "Trailer - Water Pump",
    "288": "Trailer - Cement Mixer",
    "289": "Trailer - Hot Box",
    "290": "Trailer - Power Washer - steamer",
    "291": "Trailer - Bucket Machine",
    "293": "Trailer - Thawing Machine",
    "294": "Trailer - Chipper",
    "296": "Trailer - Self-Propelled - Stumper",
    "298": "Trailer - Leaf Vac-Leaf Loader",
    "299": "Trailer - Vacuum Excavator",
    "301": "Trailer - Light Tower",
    "302": "Trailer - Centrifugal Trash Pump",
    "303": "Debri Blower - Towed Type",
    "314": "Roller-Vibrator - Asphalt",
    "315": "Sweeper - Full Size, Street",
    "316": "Sweeper - Compact, Sidewalk, Street",
    "317": "Sweeper - Industrial-Scrubber",
    "318": "Tractor - Agriculture Less than 50hp",
    "319": "Tractor - Agriculture 4x4 (Utility) Greater than 50hp",
    "321": "Loader - Compact Rubber Tire",
    "322": "Loader - Backhoe",
    "323": "Loader - Articulated",
    "324": "Loader - Skidsteer",
    "325": "Truck - Articulated Rock Truck",
    "326": "Motor Grader",
    "327": "Excavator - Mini",
    "329": "Forklift",
    "330": "Litter Vacuum - Ride-on",
    "331": "Tractor - Articulated 4x4",
    "332": "Ice Cleaning-Resurfacing (Edger)",
    "333": "Crawler Excavator , Loader, Dozer (Track)",
    "334": "Scissor Lift, Elevating Work Platform",
    "335": "Sweeper - Turf Sweeper",
    "336": "Portable Paint Stripper",
    "349": "Attachment - Rototiller",
    "350": "Attachment - Aerators",
    "353": "Attachment - Backhoe",
    "354": "Attachment - Trencher",
    "355": "Beach Comber, Cleaner",
    "357": "Attachment - Toter Lift - Slip-in Dump",
    "359": "Concrete Breaker",
    "360": "Attachment - Top Dresser",
    "361": "Attachment - 3-Point Hitch Tree Spade",
    "373": "Self Propelled - Snow Melter",
    "376": "Ice Resurfacer - Ride-on",
    "377": "Snowmobile",
    "378": "Truckster - (Toro, Cushman, Gator, EZE Go) - Utility",
    "379": "Personnel Carrier - (EZE Go, Yamaha) (Golf Cart)",
    "380": "Snow Groomer",
    "381": "Concrete Saw",
    "382": "Truckster - (Toro, Cushman, Gator, EZE Go) - With Pressure Sprayer",
    "383": "Tram Vehicle (Zoomobile)",
    "384": "Bicycle",
    "395": "Mower - Gang Reel",
    "396": "Mower - Rotary",
    "398": "Mower - Walk Behind",
    "413": "Weed Harvester",
    "415": "Sand Trap Cleaner - Sand Groomer",
    "416": "Boat (Marine Type Equipment)",
    "501": "Generators",
    "502": "Misc. Equipment"
};